language: erlang
otp_release:
  - 18.2.1
script: asdf plugin-test rebar https://github.com/Stratus3D/asdf-rebar.git
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
os:
  - linux
